version: 2

workflows:
  version: 2
  development:
    jobs:
      - build

jobs:

  build:
    machine:
      enabled: true
    environment:
      - DOCKER_IMAGE_NAME: littlefoot/circleci-elastalert:0.1.28
    steps:
      - checkout
      - run:
         name: "Docker Build"
         command: docker build -t $DOCKER_IMAGE_NAME .

      - deploy:
         name: "Docker Push"
         command: .circleci/deploy.sh
