version: 2
jobs:
  build:

    environment:
      - DOCKER_IMAGE_NAME: littlefoot/circleci-elastalert2:2.2.2-e9f59ab

    machine:
      enabled: true

    steps:
      - checkout

      - run:
         name: "Docker Build"
         command: docker build -t $DOCKER_IMAGE_NAME .

      - deploy:
         name: "Docker Push"
         command: .circleci/deploy.sh
