version: 2
jobs:
  build:
    machine:
      enabled: true
    environment:
      - DOCKER_IMAGE_NAME: littlefoot/circleci-elastalert:0.1.28
    steps:
      - checkout
      - run: docker build -t $DOCKER_IMAGE_NAME .
      - run: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run: docker push $DOCKER_IMAGE_NAME
