version: 2
jobs:
  build:

    environment:
      - DOCKER_IMAGE_NAME: littlefoot/circleci-elastalert:d2l-v0.2.4.1

    machine:
      enabled: true

    steps:
      - checkout

      - run:
         name: "Docker Build"
         command: docker build -t $DOCKER_IMAGE_NAME .

      - deploy:
         name: "Docker Push"
         command: .circleci/deploy.sh
