version: 2

workflows:
  version: 2
  development:
    jobs:
      - build

jobs:

  build:
    machine:
      enabled: true
    environment:
      - DOCKER_IMAGE_NAME: littlefoot/circleci-elastalert:unstable
    steps:
      - checkout
      - run: docker build -t $DOCKER_IMAGE_NAME .
      - deploy: .circleci/deploy.sh
